#+PROPERTY: header-args:python :session learn6 :async

* Encoding categorical variables
** Set up
#+begin_src python :results none
import openml
from sklearn.model_selection import train_test_split

DATASET_ID = 1590

openml.datasets.list_datasets(output_format="dataframe")
dataset = openml.datasets.get_dataset(DATASET_ID)

df, _, _, _ = dataset.get_data(dataset_format="dataframe")
X, y = df.drop(columns=["class"]), df["class"]
#+end_src

** Reordering categories for native-country for sorting
#+begin_src python
X['native-country'] = X['native-country'].cat.reorder_categories(
    sorted(X["native-country"].cat.categories), ordered=True
)
counts = X['native-country'].value_counts().sort_index()
counts
#+end_src

#+begin_src python
X.dtypes
#+end_src

** Changing Category type to object for testing
#+begin_src python :results none
cat_cols = X.select_dtypes(include=['category']).columns
X[cat_cols] = X[cat_cols].astype(object)
#+end_src


** Column selector

selecting columns by dtype (object)

#+begin_src python
from sklearn.compose import make_column_selector as selector
categorical_columns_selector = selector(dtype_include=object)
categorical_columns = categorical_columns_selector(X)
X_categorical = X[categorical_columns]
categorical_columns
#+end_src

** OrdinalEncoder

*** Transforming one column from categorical to numeric data.

#+begin_src python
from sklearn.preprocessing import OrdinalEncoder

education_column = X_categorical[["education"]]
encoder = OrdinalEncoder().set_output(transform="pandas")
education_encoded = encoder.fit_transform(education_column)
education_encoded
#+end_src

*** Categories preview

#+begin_src python
encoder.categories_
#+end_src

*** Encoding all categorical columns
#+begin_src python
X_encoded = encoder.fit_transform(X_categorical)
X_encoded[:5]
#+end_src

** OneHotEncoder

This makes column for each category, and sets it to 1 for samples with this category, and 0 for others.

#+begin_src python
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
education_encoded = encoder.fit_transform(education_column)
education_encoded
#+end_src

** Conclusion
*OrdinalEncoder* transforms categorical data to numerical in one column, in way that can be interpreted as order (0 < 1 < 2). It is good for categories like cloth sizes (S, M, L, XL).

The impact of this ordering assumption is dependent on the models. *Linear models* would be impacted by misordered categories while *tree-based models* would not.

Using *OrdinalEncoder*  require to ensure that:
 * the original categories (before encoding) have an ordering;
 * the encoded categories follow the same ordering than the original categories.

*One-hot encoding* categorical variables with high cardinality can cause computational inefficiency in tree-based models. Because of this, is not recommended to use *OneHotEncoder* in such cases even if the original categories do not have a given order.

** Evaluate predictive pipeline

#+begin_src python :results none
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
#+end_src

#+begin_src python :results none
model = make_pipeline(
    OneHotEncoder(handle_unknown="ignore"),
    LogisticRegression(max_iter=500),
)
#+end_src

#+begin_src python :results output
from sklearn.model_selection import cross_validate

cv_results = cross_validate(model, X_categorical, y)

for key, val in cv_results.items():
    print(f"| {key:<10} | {cv_results[key]} |")
#+end_src

#+begin_src python :results output
scores = cv_results['test_score']
print(f"Accuracy: {scores.mean():.3f} +- {scores.std():.3f}")
#+end_src
